// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant_API_Klas.Data;

#nullable disable

namespace Restaurant_API_Klas.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    partial class RestaurantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurant_API_Klas.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Email = "kenan.kurda@example.com",
                            Name = "Kenan",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            CustomerId = 2,
                            Email = "rik.riks@example.com",
                            Name = "Rik",
                            PhoneNumber = "0987654321"
                        },
                        new
                        {
                            CustomerId = 3,
                            Email = "olesia.olesias@example.com",
                            Name = "Olesia",
                            PhoneNumber = "1112223333"
                        },
                        new
                        {
                            CustomerId = 4,
                            Email = "salvatore.salvatore@example.com",
                            Name = "Salvatore",
                            PhoneNumber = "4445556666"
                        });
                });

            modelBuilder.Entity("Restaurant_API_Klas.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SpecialRequests")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TableId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            ReservationId = 1,
                            CustomerId = 1,
                            DateTime = new DateTime(2024, 6, 14, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            SpecialRequests = 1,
                            TableId = 1
                        },
                        new
                        {
                            ReservationId = 2,
                            CustomerId = 2,
                            DateTime = new DateTime(2024, 6, 14, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            SpecialRequests = 4,
                            TableId = 2
                        },
                        new
                        {
                            ReservationId = 3,
                            CustomerId = 3,
                            DateTime = new DateTime(2024, 6, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            SpecialRequests = 2,
                            TableId = 3
                        },
                        new
                        {
                            ReservationId = 4,
                            CustomerId = 4,
                            DateTime = new DateTime(2024, 6, 15, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            SpecialRequests = 2,
                            TableId = 4
                        },
                        new
                        {
                            ReservationId = 5,
                            CustomerId = 1,
                            DateTime = new DateTime(2024, 6, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            SpecialRequests = 5,
                            TableId = 2
                        });
                });

            modelBuilder.Entity("Restaurant_API_Klas.Models.Table", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("TableId");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            TableId = 1,
                            Capacity = 4,
                            Location = 1
                        },
                        new
                        {
                            TableId = 2,
                            Capacity = 2,
                            Location = 4
                        },
                        new
                        {
                            TableId = 3,
                            Capacity = 6,
                            Location = 3
                        },
                        new
                        {
                            TableId = 4,
                            Capacity = 8,
                            Location = 0
                        });
                });

            modelBuilder.Entity("Restaurant_API_Klas.Models.Reservation", b =>
                {
                    b.HasOne("Restaurant_API_Klas.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant_API_Klas.Models.Table", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Restaurant_API_Klas.Models.Customer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Restaurant_API_Klas.Models.Table", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
